// <auto-generated />
namespace pickuphockey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Session_DateRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Session_DateRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201409240342451_Session_DateRename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
