// <auto-generated />
namespace pickuphockey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Session_RecordDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Session_RecordDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201409212025457_Session_RecordDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
