// <auto-generated />
namespace pickuphockey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LockerRoom13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LockerRoom13));
        
        string IMigrationMetadata.Id
        {
            get { return "202312061956109_Locker Room 13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
